name: Update Bitcoin Price in README

on:
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: "0 0 * * *" # Daily at midnight

jobs:
  update-price:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run the script to update README.md
      - name: Update README.md
        run: npm start

      # Step 5: Commit and push changes
      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.email "2251120143@ut.edu.vn"
          git config --global user.name "vndnw"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/vndnw/bitcoin.git
          git add README.md
          git commit -m "Update Bitcoin Price on $(date)" || echo "No changes to commit"
          git push
