name: Bitcoin Price

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install

      - name: Bitcoin Price
        run: node index.js
      - name: Update README.md
        run: |
          git config --global user.email "2251120143@ut.edu.vn"
          git config --global user.name "vndnw"
          git add .
          git commit -m "Update Bitcoin Price on $(date)" || echo "No changes to commit"
          git push
